const lands = [
  {
    id: "1",
    name: "Chợ nổi Ngã Bảy",
    location: "Ngã Bảy",
    image: require("../assets/images/ngabay.jpg"),
    audio: require("../assets/audio/dlngabay.mp3"),
    url: "https://www.youtube.com/watch?app=desktop&v=aQDFYXksw7U",
    details: `Chợ nổi Ngã Bảy hay còn gọi là chợ nổi Phụng Hiệp thuộc thị xẫ Ngã Bảy được hình thành từ năm 1915. Đây là chợ nổi rất nổi tiếng của tỉnh Hậu Giang và từng được người Pháp gọi là"Ngôi sao Phụng Hiệp. Bởi nơi đây hoạt động buôn bán, trao đổi hàng hóa diễn ra rất sầm uất. Mặt khác đây còn là địa điểm rất thu hút và hấp dẫn khách du lịch. Hiện tại, để đảm bảo an toàn giao thông đường thủy chợ nổi Ngã Bảy đã được kéo dài về Kênh Ba Ngàn trên sông Cái Côn, thuộc ấp Mái Dầm, xã Đại Thành, cách vị trí cũ khoảng 3km`,
  },
  {
    id: "2",
    name: "Lung Ngọc Hoàng",
    location: "Xã Phương Bình, huyện Phụng Hiệp",
    image: require("../assets/images/lungngochoang.jpg"),
    audio: require("../assets/audio/dlngochoang.mp3"),
    url: "https://www.youtube.com/watch?v=Vtv46HA2FFE",
    details: `Với diện tích khoảng 2800ha thuộc hai xã Phương Bình và Phương Phú(huyện Phụng Hiệp). Khu bảo tồn thiên nhiên Lung Ngọc Hoàng không chỉ được mệnh danh là lá phổi xanh của ĐBSCL mà còn là nơi bảo tồn đa dạng sinh học thuộc dạng độc đáo nhất cả nước hiện nay. Với trên 330 loài thực vật trong đó có 56 loài mới phát hiện và 206 loài động vật trong đó có loài đang nằm trong sách đỏ Việt Nam và thế giới như rái cá lông mũi, rùa nắp, rắn hổ mang.`,
  },
  {
    id: "3",
    name: "Công viên Xà No",
    location: "TP. Vị Thanh",
    image: require("../assets/images/congvienxano.jpg"),
    audio: require("../assets/audio/dlxano.mp3"),
    url: "https://www.vietfuntravel.com.vn/blog/tham-quan-cong-vien-xa-no-o-vi-thanh-hau-giang.html",
    details: `Bờ kè kênh xáng Xà No có chiều dài toàn tuyến là 2 km chạy qua địa phận các huyện: Châu Thành A, Vị Thủy, Thành phố Vị Thanh. Đây là một trong những công trình tiêu biểu chào mừng Đại lễ kỷ niệm 1000 măm Thăng Long-Hà Nội và đây cũng là một trong những công trình bờ kè sông dài nhất Việt Nam hiện nay. Công viên Xà No - Hậu Giang nằm trong nội ô thành phố Vị Thanh dọc theo hai bên bờ kè kênh xáng dài hơn 15km được trồng rất nhiều cây xanh như: cau đỏ java, dừa kiểng Philippin, hoa ban, hoa hậu, liễu đỏ, bằng lăng,..kết hợp với các tác phẩm nghệ thuật điêu khắc bằng đá trắng tạo nên một khung cảnh thật thơ mộng, lãng mạng.`,
  },

  {
    id: "4",
    name: "Du lịch sinh thái Phú Hữu",
    location: "Xã Phú Hữu, huyện Châu Thành",
    image: require("../assets/images/sinhthaiphuhuu.jpg"),
    audio: require("../assets/audio/dlphuhuu.mp3"),
    url: "https://www.youtube.com/watch?v=vFu0-CHSzPM",
    details: `Trung tâm du lịch sinh thái Phú Hữu tọa lạc tại ấp Phú Hữu, huyện Châu Thành, tỉnh Hậu Giang, cách thành phố Vị Thanh hơn 50km và từ TP. Cần Thơ chỉ khoảng 60 phút đi bằng tàu, du khách có thể đi ngang ngắm cầu Cần Thơ, qua một phần của sông Hậu. Đi bằng đường bộ, từ cầu Quang Trung - TP. Cần Thơ chỉ mất 20 phút là du khách đã đến với Trung tâm Du lịch sinh thái Phú Hữu.`,
  },
  {
    id: "5",
    name: "Du lịch sinh thái Việt-Úc",
    location: "Xã Vĩnh Tường, huyện Vị Thủy",
    image: require("../assets/images/sinhthaivietuc.jpg"),
    audio: require("../assets/audio/dlvietuc.mp3"),
    url:"https://www.youtube.com/watch?v=9Xev2ywFZH0",
    details: `Được quy hoạch trên diện tích khoảng 145,92ha tọa lạc tại xã Vĩnh Tường, huyện Vị Thủy, tỉnh Hậu Giang, cách TP. Vị Thanh 9km về hướng đông nam, với tổng số vốn đầu tư trên 3 triệu USD. Hiện khu du lịch sinh thái này đang được công ty TNHH Việt Úc - Hậu Giang đầu tư xây dựng thành khu du lịch, hệ sinh thái tự nhiên rừng ngập nước gồm nhiều khu chức năng: khu điều hành và quản lý, khu trưng bày văn hóa dân tộc và dịch vụ tổng hợp, khu nghỉ dưỡng, khu nhà vườn tái định cư kết hợp trồng cây ăn trái, khu nuôi trồng thủy sản nước ngọt kết hợp dịch vụ hỗ trợ ăn uống, nghe hát đàn ca tài tử Nam Bộ, câu cá, đặt lợp, du ngoạn bằng tàu, khu spa, massage,...và khu rừng tràm nguyên sinh`,
  },
  {
    id: "6",
    name: "Rẫy khóm cầu Đúc",
    location: "Xã Tân Tiến, TP. Vị Thanh",
    image: require("../assets/images/raykhomcauduc.jpg"),
    audio: require("../assets/audio/dlkhomcauduc.mp3"),
    url:"https://www.youtube.com/watch?v=-dQnaysx29U",
    details: `Cách thành phố Vị Thanh khoảng 10km ven QL61 về hướng Rạch Giá, nằm trên địa bàn hai xã Tân Tiến và Hỏa Tiến. Khóm Cầu Đúc có mặt ở vùng đất này hơn 100 năm qua. Khi nơi này có cây cầu đúc bằng xi măng đầu tiên, bà con gọi vùng đất của mình là xóm Cầu Đúc và tên Khóm Cầu Đúc cũng từ đây mà có. Hiện nay Khóm Cầu Đúc đã trở thành một loại đặc sản có mặt trên thị trường cả nước bởi hương vị ngọt thanh rất đặc trưng không bất kỳ loại khóm nào. Năm 2006 Hậu Giang đã chọn Khóm Cầu Đúc để xây dựng thương hiệu cho tỉnh.`,
  },
  {
    id: "7",
    name: "Quan Đế Miếu",
    location: "Phường 4 TP. Vị Thanh",
    image: require("../assets/images/quandemieu.jpg"),
    audio: require("../assets/audio/dldequan.mp3"),
    url:"https://www.youtube.com/watch?v=G4lQDLQXQqg&t=33s",
    details: `Quan Đề Miều tọa lạc tại khu vực 1, phường V, thành phố Vị Thanh. Được thành lập năm 1970 do người Hoa tỉnh Quảng Đông, Trung Quốc di cư sang Việt Nam và sống ở khu vực thành phố Vị Thanh sáng lập. Qua nhiều lần trùng tu, đến nay Quan Đế Miếu đã khang trang hơn với lối kiến trúc mang đậm nét chùa cổ Trung Hoa, chánh điện thờ Quan Thánh Đế Quân, Thiên Hậu Thánh Mẫu, Phước Đức chấn thành, Mã Tướng quân. Hiện nay nơi đây còn thành lập phòng thuốc nam bắt mạch, hốt thuốc và châm cứu từ thiện`,
  },
  {
    id: "8",
    name: "Nhà thờ Vị Hưng",
    location: "Phường 4 TP. Vị Thanh",
    image: require("../assets/images/nhathovihung.jpg"),
    audio: require("../assets/audio/dlvihung.mp3"),
    url:"https://thamhiemmekong.com/thong-tin-du-lich-mien-tay/kien-truc-doc-dao-cua-nha-tho-vi-hung-o-hau-giang.html",
    details: `Nhà thờ Vị Hưng tọa lạc tại khu vực 2, phường IV, thành phố Vị Thanh. Nhà thờ là một công trình uy nghi mang đậm kiến trúc hiện đại được xây dựng trên một khu đất rộng nằm bên cạnh dòng kênh Xà No huyết mạch giao thương của các tỉnh miền Tây. Xung quanh nhà thờ là khuôn viên thoáng mát, đối diện với khu hành chính UBND tỉnh và công viên Chiến Thắng tạo nên vẽ đẹp trang nhã cho Nhà Thờ. Vào dịp lễ Giáng Sinh hàng năm, đây là nơi tập trung đông đảo giáo dân đến tham quan, dự lễ.`,
  },
  {
    id: "9",
    name: "Chùa ARANHUT",
    location: "Thị trấn Cái Tắc, huyện Châu Thành A",
    image: require("../assets/images/chuaaranhut.png"),
    audio: require("../assets/audio/dlchuaaranhut.mp3"),
    url:"https://www.youtube.com/watch?v=jGfBDxMS4qY",
    details: `Vào khoảng năm 1632, người Khmer ở địa phương đã có ý định xây dựng một ngôi chùa để làm nơi tín ngưỡng tôn giáo và sinh hoạt tinh thần vào các dịp lễ hội. Thế là chùa Aranhứt “mọc” lên nhờ sự đồng lòng của mọi người. Trải qua năm tháng, chùa Aranhứt đã trở thành điểm tựa tinh thần của biết bao thế hệ người Khmer nơi đây.Những năm kháng chiến chống Pháp và đánh Mỹ, chùa Aranhứt từng là nơi nuôi chứa cán bộ cách mạng hoạt động ở địa phương. Cũng vì vậy mà chùa nhiều lần bị bọn giặc đánh phá. Nặng nhất là vào năm 1968, khi Mỹ ném bom trúng ngay khu vực chính điện, khiến ngôi chùa gần như bị phá hủy hoàn toàn. Sau này, phật tử ở khắp nơi đã quyên góp tiền bạc để xây dựng lại chùa. Sau nhiều lần xây dựng, sửa chữa, đến nay, chùa Aranhứt đã khang trang hơn trước rất nhiều với 1 chính điện, 3 tăng xá…, trên diện tích hơn 12.000m2. Cũng giống như bao ngôi chùa Khmer khác, chùa Aranhứt có kiểu kiến trúc độc đáo với những nét chạm trổ, điêu khắc đặc trưng của các ngôi chùa Khmer Nam bộ. Ngày nay, chùa Aranhứt tiếp tục trở thành nơi sinh hoạt, tín ngưỡng tôn giáo của các phật tử ở địa phương và gần xa. Mỗi dịp lễ, tết của người Khmer, bà con Khmer và người Kinh trong ấp và các ấp lân cận đến chùa rất đông để thắp nhang, cầu nguyện cho gia đình mình gặp nhiều may mắn trong cuộc sống. Nhân cơ hội có đông đồng bào Khmer đến chùa, Ban quản trị chùa luôn cố gắng tuyên truyền các chủ trương, đường lối đúng đắn của Đảng và Nhà nước để bà con hiểu rõ và thực hiện tốt.`,
  },
  {
    id: "10",
    name: "Thiền viện Trúc Lâm",
    location: "Phường Vĩnh Tường, thị xã Long Mỹ",
    image: require("../assets/images/thienvientruclam.jpg"),
    audio: require("../assets/audio/dltruclam.mp3"),
    url:"https://www.youtube.com/watch?v=8VOphDuSk98",
    details: `Nếu đi từ Thành phố Vị Thanh (Hậu Giang) về Cần Thơ theo Quốc lộ 61 cũ qua Cái Tắc, đến ngã ba Vĩnh Tường, khu vực Bình Tân, phường Vĩnh Tường, thị xã Long Mỹ, tỉnh Hậu Giang, bạn sẽ nhìn thấy một cụm công trình kiến trúc tôn giáo rất quy mô đó chính là Thiền Viện Trúc Lâm Hậu Giang. Với vị trí đắc địa rất thuận lợi cho việc thăm viếng sinh hoạt tín ngưỡng của người dân trong tỉnh và khách thập phương du lịch Hậu Giang đến tham quan chiêm bái.Thiền viện Trúc Lâm Hậu Giang là nơi tu theo Thiền phái Trúc Lâm Yên Tử một dòng thiền mang đậm bản sắc văn hóa dân tộc Việt Nam do vua Trần Nhân Tông khai mở và phát triển. Ông là vị vua thứ ba triều đại Nhà Trần, sau khi lãnh đạo tinh thần dân tộc chống quân Nguyên Mông, đất nước yên bình, Ngài nhường ngôn lại cho con, lên non Yên Tử xuất gia tu hành. Sau khi đắc đạo, Ngài dung hợp 3 Thiền phái trước đó và sáng lập thành Thiền phái Trúc lâm.Thiền viện Trúc Lâm Hậu Giang hoàn thành có ý nghĩa quan trọng trong việc bảo tồn và phát huy những giá trị truyền thống của văn hóa Phật giáo, kết nối các di tích lịch sử, văn hóa truyền thống của địa phương, và là điểm nhấn du lịch văn hóa tâm linh của mảnh đất Hậu Giang hiền hòa.Dáng vóc ngôi thiền viện xây dựng theo kiến trúc mỹ thuật Phật giáo thời Lý, Trần trên diện tích 40.000 m2. Bao gồm các hạng mục: Chánh điện, nhà Tổ, lầu chuông, lầu trống, Cổng tam quan, nhà nghỉ chân, tôn tượng Quan Âm lộ thiên, miếu thờ Mẹ Âu Cơ, giảng đường, trai đường, nhà trụ trì, nhà khách, thư viện, Tăng xá, Ni xá…`,
  },
];

export default lands;
